---
title: "COMPASS_TEMPEST_Collate_Dionex_2022_Data"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: html_document
---

```{r}
Sample_Year = "2022"
Run_notes = ""
```

```{r setup, include=FALSE}

#Packages that are required 
lapply(c(
  "dplyr", "ggplot2", "ggpubr", "stringr",
  "purrr", "tidyverse", "here", "broom", "tibble",
  "googledrive", "googlesheets4", "data.table", 
  "matrixStats", "gridExtra", "grid", "readxl", "stringr"), 
  library, character.only = TRUE)

#Packages for loading metadata
require(pacman)
pacman::p_load(janitor, # useful for simplifying column names
               googlesheets4, # read_sheet 
               googledrive, # drive_ functions
               plotrix,
               here) 

common_tz = "Etc/GMT+5"

Sys.setenv(TZ = "America/New_York")
```

#Read in and collate all the files in the Processed Data folder 
```{r}

#Pull data from Allison's "TEMPORARY" folder
##Code for creating these datasets is already in the 2022 folder

##Lysimeter data
lys_data <- read.csv(here("processing_scripts/DOC/TEMPORARY/", "TMP_PW_GRIDSONLY_NPOCTDN_2022_L1.csv"))

lys_data$date <- as.Date(lys_data$collection_datetime)
lys_data$date <- gsub("-", "", lys_data$date)

lys_data$time <- substr(lys_data$collection_datetime, 12, 16)
lys_data$time <- gsub(":", "", lys_data$time)

##Remove samples where lysimeter was empty
lys_data <- subset(lys_data, sample_name != "Lysimeter Empty")

##Fix different sample IDs
lys_data$sample_name <- gsub("_PW_", "_", lys_data$sample_name)
lys_data$sample_name <- gsub("_15cm_", "_", lys_data$sample_name)


##SourceWater data
sw_data <- read.csv(here("processing_scripts/DOC/TEMPORARY/", "TMP_SOURCE_NPOCTDN_2022_L1.csv"))

#Format sample IDs
sw_data$date <- as.Date(sw_data$datetime)
sw_data$date <- gsub("-", "", sw_data$date)

sw_data$time <- substr(sw_data$datetime, 12, 16)
sw_data$time <- gsub(":", "", sw_data$time)

sw_data$grid <- "Source"

sw_data <- sw_data %>%
  rename(
    collection_datetime = datetime
  )


##Combine SW and lysimeter data
all_data <- bind_rows(lys_data, sw_data)

all_data <- all_data %>% 
    mutate(
    plot = case_when(
      plot == "Control" ~ "C",
      plot == "Freshwater" ~ "FW",
      plot == "Saltwater" ~ "SW",
      TRUE ~ plot  # keep everything else unchanged
    )
  ) 

all_data <- all_data %>%
  rename(
    Time = time, 
    Plot = plot, 
    Grid = grid, 
    Site = site, 
    Collection_Date_YYYYMMDD = date
  )


##Add Time of Day column (AM < 1200, PM > 1200)
all_data$Collection_End_Time_24hrs <- as.numeric(all_data$Time)

##For 20220518, 20220520, and Sourcewater, need to change times to T0-T7 in Sample ID
all_data <- all_data %>% 
  group_by(Plot, Grid, Collection_Date_YYYYMMDD) %>% 
  arrange(Collection_End_Time_24hrs, .by_group = TRUE) %>% # Sort by Time ascending
  mutate(Event_Time = paste0("T", row_number())) %>% 
  ungroup()

all_data <- all_data %>% 
  mutate(Sample_ID = ifelse(Collection_Date_YYYYMMDD == "20220518" | Collection_Date_YYYYMMDD == "20220520" | Grid == "Source", paste(Site, Plot, Grid, Collection_Date_YYYYMMDD, Event_Time, sep = "_"), paste(Site, Plot, Grid, Collection_Date_YYYYMMDD, sep = "_")))

all_data3 <- all_data %>% 
  select("Sample_ID", "doc_mg_l", "tdn_mg_l", "doc_flag", "tdn_flag", "Time", "Plot", "Grid", "Collection_End_Time_24hrs", "Collection_Date_YYYYMMDD")

```

## Pull in active porewater tracking inventory sheet from Google Drive: 
```{r rest of metadata, include=FALSE}

# Run these to pull the TEMPEST porewater metadata into GitHub if not already there
inventory_directory <- "https://docs.google.com/spreadsheets/d/1sFWq-WKhemPzbOFInqhCu_Lx0lsO6a_Z/edit#gid=496164093"

drive_download(inventory_directory, overwrite = TRUE)

sheet_names <- excel_sheets("TEMPEST_PorewaterInventory_May2022_Present.xlsx")
sheet_names

raw_metadata_lys <- read_excel("TEMPEST_PorewaterInventory_May2022_Present.xlsx", sheet = "Porewater - Individual", skip = 3)

raw_metadata_sw <- read_excel("TEMPEST_PorewaterInventory_May2022_Present.xlsx", sheet = "Source Water", skip = 3, col_types = c(
  "text", "text","numeric","text","text","text","text","date", "text","text"))


```


##Create similar sample IDs to match with run samples 
```{r pull in metadata for later, include=FALSE}

###LYSIMETER SAMPLES###
#select DOC samples 
#select 2022 samples
raw_metadata_lys_year <- raw_metadata_lys %>%  
  filter(str_detect(Sample_ID, "DOC|of")) %>% 
  filter(str_detect(Sample_ID, Sample_Year))

##Remove DOC from the sample IDs that have it
raw_metadata_lys_year$Sample_ID <- gsub("_DOC_", "_", raw_metadata_lys_year$Sample_ID)
raw_metadata_lys_year$Sample_ID <- gsub("_DOC _", "_", raw_metadata_lys_year$Sample_ID)

#separate samples into columns
raw_metadata_lys_year <- raw_metadata_lys_year %>%
  separate(
    col = Sample_ID,
    sep = "_",
    into = c("Site", "Plot", "Source" ,"Grid", "Depth", "Collection_Date", "Event_Time"),
    remove = FALSE)


##Change "1of3" to T1
raw_metadata_lys_year$Event_Time <- gsub("1of1", "T1", raw_metadata_lys_year$Event_Time)
raw_metadata_lys_year$Event_Time <- gsub("1of2", "T1", raw_metadata_lys_year$Event_Time)
raw_metadata_lys_year$Event_Time <- gsub("1of3", "T1", raw_metadata_lys_year$Event_Time)

raw_metadata_lys_year$Event_Time <- gsub("2of2", "T2", raw_metadata_lys_year$Event_Time)
raw_metadata_lys_year$Event_Time <- gsub("2of3", "T2", raw_metadata_lys_year$Event_Time)

raw_metadata_lys_year$Event_Time <- gsub("3of3", "T3", raw_metadata_lys_year$Event_Time)


#create IDs from what was collected for comparison later
raw_metadata_lys_ids <- raw_metadata_lys_year %>%
  mutate(DOC_ID = paste(Site,
                          Plot,
                          Grid,
                          Collection_Date_YYYYMMDD, 
                          Event_Time, 
                          sep = "_"))

raw_metadata_lys_ids$DOC_ID <- gsub("_NA", "", raw_metadata_lys_ids$DOC_ID)


###SOURCEWATER SAMPLES###
#select DOC samples
#select 2022 samples
raw_metadata_sw_year <- raw_metadata_sw %>%  
  filter(str_detect(Vial_ID, "HR")) 

##Set Collection date because it's not in the metadata
raw_metadata_sw_year$Collection_Date_YYYYMMDD <- 20220622

##Fix collection Time
raw_metadata_sw_year$time <- substr(raw_metadata_sw_year$Collection_Time_24hrs, 12, 16)
raw_metadata_sw_year$Collection_End_Time_24hrs <- gsub(":", "", raw_metadata_sw_year$time)

##Change HR# to T#
raw_metadata_sw_year$DOC_ID <- gsub("HR", "T", raw_metadata_sw_year$Vial_ID)

##Add in the date
raw_metadata_sw_year$DOC_ID <- gsub("SOURCE_T", "SOURCE_20220622_T", raw_metadata_sw_year$DOC_ID)

#separate samples into columns
raw_metadata_sw_year <- raw_metadata_sw_year %>%
  rename(EST_EDT = "EST/EDT")

#create IDs from what was collected for comparison later
raw_metadata_sw_combined <- raw_metadata_sw_year %>%
  rename("Notes" = "Notes:")

#combine porewater and sourcewater samples
raw_metadata_lys_ids$Collection_End_Time_24hrs <- as.character(raw_metadata_lys_ids$Collection_End_Time_24hrs)
doc_metadata <- bind_rows(raw_metadata_lys_ids, raw_metadata_sw_combined)

#remove old ID's
doc_metadata$Sample_ID <- NULL

#Rename columns that have missing data
doc_metadata <- doc_metadata %>%
  rename(Grid_meta = Grid, 
         Plot_meta = Plot, 
         Collection_End_Time_24hrs_meta = Collection_End_Time_24hrs, 
         Collection_Date_YYYYMMDD_meta = Collection_Date_YYYYMMDD)


colnames(doc_metadata)

# head(doc_metadata)

```


## Check to see if samples run match metadata & merge info
```{r check sample ids with metadata, echo=FALSE, warning = FALSE}

#check to see if all samples are present in the metadata 
all_data3$Sample_ID <- toupper(all_data3$Sample_ID)
doc_metadata$DOC_ID <- toupper(doc_metadata$DOC_ID)

all_present <- all(all_data3$Sample_ID %in% doc_metadata$DOC_ID)

if (all_present) {
  message("All sample IDs are present in metadata.")
} else {
  message("Some sample IDs are missing from metadata.")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(all_data3$Sample_ID, doc_metadata$DOC_ID)
  print(missing_ids)
}


#merge metadata with sample run data 
merged_data <- all_data3 %>%
  left_join(doc_metadata, by = c("Sample_ID" = "DOC_ID"))

##Add Depth for PW samples 
merged_data <- merged_data %>% 
  mutate(Depth = ifelse(Grid != "Source", "15cm", NA))
merged_data$Sample_ID <- paste(merged_data$Sample_ID, merged_data$Depth, sep = "_")
merged_data$Sample_ID <- gsub("_NA", "", merged_data$Sample_ID)

```


## Convert data from mg/L to uMoles/L 
```{r, Unit Conversion, include=FALSE}

  mw_c <- 12   #molecular weight of Carbon 
  mw_n <- 14  #molecular weight of Nitrogen
  Con1 <- 1000       # conversion factor value
  Con2 <- 1000000    # conversion factor value 

#convert npoc and tdn from mg/L to uMoles/L 
merged_data <- merged_data %>%
  mutate(
    doc_uM = (((as.numeric(merged_data$doc_mg_l))/Con1)/mw_c)*Con2, 
    tdn_uM = (((as.numeric(merged_data$tdn_mg_l))/Con1)/mw_n)*Con2
  )

```


## Visualize Data by Plot   
```{r Visualize Data, echo=FALSE, warning=FALSE}

#Plot samples to get a first look at concentrations (sanity check)
data_plotting <- merged_data %>%
  subset(!is.na(Plot))

#Order by Plot from C, FW, SW
data_plotting <- data_plotting %>% 
    mutate(
    Plot_1 = case_when(
      Plot == "C" ~ "Control",
      Plot == "FW" ~ "Freshwater",
      Plot == "SW" ~ "Saltwater",
      TRUE ~ Plot  # keep everything else unchanged
    )
  ) %>%
  mutate(Plot_1 = factor(Plot_1, levels = c("Control", "Freshwater", "Saltwater")))

data_plotting$doc_mg_l <- as.numeric(data_plotting$doc_mg_l)
data_plotting$tdn_mg_l <- as.numeric(data_plotting$tdn_mg_l)

#group the data for plotting
data_plotting <- data_plotting %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()

#Plot data and change colors based on Zone:
viz_doc_plot <- ggplot(data_plotting, aes(x = row_num, y = doc_mg_l, fill = Plot_1)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) +
  facet_wrap(~ Plot_1, scales="free") +
  scale_fill_manual(values = c(
    "Control" = "springgreen2",
    "Freshwater" = "cyan2",
    "Saltwater" = "violetred2"
  )) +
  theme_classic() +
  theme(axis.text.x = element_blank()) +
  labs(x = " ", y = "DOC (mg/L)", title = "Samples: DOC") +
  scale_x_discrete(drop = TRUE)


viz_tdn_plot <-  ggplot(data_plotting, aes(x = row_num, y = tdn_mg_l, fill = Plot_1)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) +
  facet_wrap(~ Plot_1, scales="free") +
  scale_fill_manual(values = c(
    "Control" = "springgreen2",
    "Freshwater" = "cyan2",
    "Saltwater" = "violetred2"
  )) +
  theme_classic() +
  theme(axis.text.x = element_blank()) +
  labs(x = " ", y = "TDN (mg/L)", title = "Samples: TDN") +
  scale_x_discrete(drop = TRUE)

ggarrange(viz_doc_plot, viz_tdn_plot, nrow=2, ncol=1)


```

## Write the 2022 file out to the folder 
```{r, echo=FALSE}
colnames(merged_data)

final_data <- merged_data %>%
  mutate(
    Depth_cm = Depth, 
    Run_notes = Run_notes, 
    Field_notes = Notes, 
    Project = "COMPASS", 
    Site = "TEMPEST", 
    Analysis_runtime = "NA", 
    Analyte = "DOC"
  ) %>%
  rename(
    npoc_mgL = doc_mg_l, 
    npoc_uM = doc_uM, 
    npoc_flag = doc_flag, 
    tdn_mgL = tdn_mg_l, 
    plot = Plot, 
    grid = Grid
  ) %>%
 select(
    Project, Site, plot, grid, Depth_cm, Analyte, Sample_ID, 
    npoc_mgL, npoc_uM, npoc_flag, tdn_mgL, tdn_uM, tdn_flag, Analysis_runtime,
    Run_notes, Field_notes, Evacuation_date_YYYMMDD, Collection_Date_YYYYMMDD, 
    Collection_Start_Time_24hrs, Collection_End_Time_24hrs, EST_EDT, Volume_mL
    # list columns in the order you want them
  )

colnames(final_data)

write.csv(final_data, "COMPASS_TEMPEST_DOC_2022.csv", row.names = FALSE)

```

