---
title: "TEMPEST: Porewater pH"
author: "2023-2025 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(knitr)
```

##Grab 2023 and 2024 and 2025 All Data Files
```{r Pull in 2022-2024 data files, message=FALSE, include=FALSE}

#read in 2023 Dionex Data:
dat23 <- read.csv("Raw Data/TMP_PW_pH_2023_L1.csv")
# head(dat24)
colnames(dat23)

#read in 2024 Dionex Data:
dat24 <- read.csv("Raw Data/TMP_PW_pH_2024_L1.csv")
# head(dat24)
colnames(dat24)

#read in 2025 Dionex Data:
dat25 <- read.csv("Raw Data/TMP_PW_pH_2025_L1.csv")
# head(dat25)
colnames(dat25)

raw_dat <- bind_rows(dat23, dat24, dat25)

##Convert Collection Date into Date format
raw_dat$Collection_Date_Time <- as.POSIXct(raw_dat$datetime, format = "%Y-%m-%dT%H:%M:%SZ", tz = "US/Eastern")

##Extract Year and month from Collection Date
raw_dat$Year <- format(raw_dat$Collection_Date_Time, format = "%Y")
raw_dat$Month <- format(raw_dat$Collection_Date_Time, format = "%m")
raw_dat$Day <- format(raw_dat$Collection_Date_Time, format = "%d")

##Add flags for pH values outside of range (3.5-8)
raw_dat$pH_flag <- ifelse(raw_dat$pH < 3.5 | raw_dat$pH > 8, "pH value is outside the typical range", NA)

colnames(raw_dat)

all_dat <- raw_dat %>%
  mutate(
    Project = "TEMPEST"
  ) %>%
  rename(
    Zone = plot, 
    Grid = grid, 
    Evacuation_Date = evacuation_date, 
    temperature_flag = flag
  )%>%
  dplyr::select(
         Project, Year, Month, Day, 
         Zone, Grid, pH, collection_temp_C, 
         Collection_Date_Time, Evacuation_Date, temperature_flag, pH_flag
        # list columns in the order you want them
  )

```


##Make Relevant Metadata Sheet
```{r make metadata, include = FALSE}

#pull the column names from the all_dat dataframe and create a new dataframe with them 
metadat <- data.frame(Column_Names = colnames(all_dat))
metadat
colnames(all_dat)
metadat$Description <- ""
metadat$Units <- ""
metadat$Instrument_ifapplicable <- ""

#add information about each line: 

metadat$Description <- c("Project name", 
                         "Year of sample collection", 
                         "Month of sample collection", 
                         "Day of sample collection", 
                         "Plot where sample collected (Control, Freshwater, Saltwater)", 
                         "Grid where sample collected (Letter + Number)", 
                         "pH of sample", 
                         "Temperature at time of collection in Celsius", 
                         "Date and Time of sample collection", 
                         "Date of sample evacuation",
                         "Flag to indicate if temperature was not recorded", 
                         "Flag to indicate if the pH is outside of the typicaly range")

metadat$Units <-       c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "degrees Celsius",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA")

metadat$Instrument_ifapplicable <-  
  
                       c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA")

```

##Write out files
```{r write out combined data and metadata, include=FALSE}

#write out a csv of all the data to the main folder: 
write.csv(all_dat, "COMPASS_TEMPEST_pH_AllData.csv")


#write out a csv of the metadata associated with the data: 
write.csv(metadat, "COMPASS_TEMPEST_pH_Metadata.csv")

```

## Visualize Data by Zone   
```{r Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Define Zones for plotting
data_plotting <- all_dat %>% 
  mutate(Zone_1 = factor(Zone, levels = c("Control", "Freshwater", "Saltwater")))

#Plot data by year and change colors based on Zone:
viz_pH_plot <- ggplot(data_plotting, aes(x = as.character(Year), y = pH, fill = Zone_1)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_wrap( ~ Zone_1, scales="free") +
  scale_fill_manual(values = c(
    "Control" = "springgreen2",
    "Freshwater" = "cyan2",
    "Saltwater" = "violetred2"
  )) +
  theme_classic() +
  labs(x = " ", y = "pH", title = "Samples: Chloride") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 20))+ 
  theme(legend.position = "none")

viz_pH_plot

```

## Summarized data for Site and Zone 
```{r Summarize and Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Summarize SO4 and Cl by Date and Zone
pH_avg <- data_plotting %>%
  group_by(Collection_Date_Time, Zone_1) %>%
   dplyr::summarize(mean_pH = mean(pH, na.rm=TRUE),
            sd_pH = sd(pH, na.rm=TRUE))

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2023-01-01", "2024-01-01", "2025-01-01"))

viz_pH_plot_avgs <- ggplot(pH_avg, aes(x = Collection_Date_Time, y = mean_pH, color = Zone_1)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_pH - sd_pH, ymax = mean_pH + sd_pH), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Zone_1, scales="free_y", ncol = 1) +
  scale_color_manual(values = c(
    "Control" = "springgreen2",
    "Freshwater" = "cyan2",
    "Saltwater" = "violetred2"
  )) +
  theme_classic() +
  labs(x = "Date", y = "pH", title = "Samples: pH") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") + # Format x-axis labels
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  theme(legend.position = "none")+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

viz_pH_plot_avgs

```

## Boxplot summary
```{r Overall Boxplot, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

data_plotting$Collection_date_char <- as.Date(data_plotting$Collection_Date_Time)
data_plotting$Collection_date_char <- gsub("-", "", data_plotting$Collection_date_char)

##Boxplot Summarize pH by Date, Site, and Zone
viz_pH_boxplot <- ggplot(data_plotting, aes(x = Collection_date_char,  y = pH, fill = Zone_1)) +
  geom_boxplot() + 
  facet_wrap( ~ Zone_1, scales="free_y", ncol = 1) +
  # scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    "Control" = "springgreen2",
    "Freshwater" = "cyan2",
    "Saltwater" = "violetred2"
  ), labels = c("Control", "Freshwater", "Saltwater")) +
  theme_classic() +
  labs(x = " ", y = "pH", title = "TEMPEST Porewater: pH") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 30))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  theme(legend.position = "none")

viz_pH_boxplot

# # Save as a PNG
# png("COMPASS_TEMPEST_pH_alldata.png", width = 2000, height = 1200, res = 100)
# print(viz_pH_boxplot)  # For ggplot objects, use print()
# dev.off()

```

##Calculate summary metrics
```{r Additional summary metrics, include=FALSE, dpi = 300}
# It would also be great to add to our collation codes a summary chunk that will calculate value ranges, means, and standard deviations (and errors) for each site, zone, depth for each year; also for each site zone, depth overall; and for each site and zone overall so that we have some easy access to metrics. Was just thinking this might be helpful today when re-collating the DIC data.

colnames(data_plotting)

##Metrics for each zone for each year
summary_by_year <- data_plotting %>%
  group_by(Year, Zone_1) %>%
   reframe(
     min_pH = min(pH, na.rm=TRUE),
     max_pH = max(pH, na.rm=TRUE), 
     mean_pH = mean(pH, na.rm=TRUE), 
     sd_pH = sd(pH, na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 4)) 

##Metrics for each zone for all years
summary_all_years <- data_plotting %>%
  group_by(Zone_1) %>%
   reframe(
     min_pH = min(pH, na.rm=TRUE),
     max_pH = max(pH, na.rm=TRUE), 
     mean_pH = mean(pH, na.rm=TRUE), 
     sd_pH = sd(pH, na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 4)) 

```

## Summary Tables
```{r Summary table metrics, echo = FALSE, message = FALSE, dpi = 100}

library(kableExtra)

kable(
  summary_by_year[, c("Year", "Zone_1", "min_pH",	"max_pH",	"mean_pH")],  
  format = "latex",
  booktabs = TRUE,
  caption = "Summary Statistics by Year"
) %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)

kable(
  summary_all_years[, c("Zone_1", "min_pH",	"max_pH",	"mean_pH")],  
  format = "latex",
  booktabs = TRUE,
  caption = "Summary Statistics by Zone"
) %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)

```

##Write out summarized data
```{r write out summarized data, include=FALSE}

#write out a csv of all the data to the main folder: 
write.csv(summary_by_year, "COMPASS_TEMPEST_PW_pH_Summarized_By_Year.csv")

#write out a csv of the metadata associated with the data: 
write.csv(summary_all_years, "COMPASS_TEMPEST_PW_pH_Summarized_Years_Combined.csv")

```



