---
title: "COMPASS_TEMPEST_Collate_All_Porewater_Data"
author: "Zoe Read"
date: "`r Sys.Date()`"
output: html_document
---

##Load required packages
```{r setup, include=FALSE}

library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(purrr)

#Packages for loading metadata
require(pacman)
pacman::p_load(janitor, # useful for simplifying column names
               googlesheets4, # read_sheet 
               googledrive, # drive_ functions
               plotrix,
               here) 

# detach("package:raster", unload = TRUE)

```

#Read in and collate all the collated analyte files
```{r}

##Should negative concentrations all be converted to zero? 

# Event samples: 
# 2022: T#
# 2023: AM/PM for PW, T# for Sourcewater
# 2023: T# and AM/PM for PW, AM/MID/PM for Sourcewater, High and Low Tide for Estuary Sourcewater (Removed AM/PM from PW ID, converted HT/LT to AM/PM for Estuary Sourcewater)

##Collated data by analyte
##Desired Sample ID format: TMP_FW_H6_15CM_20220620_T0

####DOC####
DOC <- read.csv("DOC/COMPASS_TEMPEST_DOC_AllData.csv")
DOC1 <- DOC %>% 
  dplyr::select(c("Sample_ID", "npoc_mgL", "npoc_uM", "npoc_flag", "tdn_mgL", "tdn_uM", "tdn_flag")) %>% 
  mutate(Sample_ID = toupper (Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_15_", "_15CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_30_", "_30CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_50_", "_50CM_", Sample_ID)) %>% 
  mutate(Sample_ID = ifelse(str_detect(Sample_ID, "SOURCE"), gsub("20220622_T", "20220622_HR", Sample_ID), Sample_ID)) %>% 
  mutate(Sample_ID = gsub("RAIN_20241212", "RAINWATER_20241212", Sample_ID)) %>% 
  distinct() 

DOC2 <- DOC1 %>%
  mutate(Plot = stringr::str_extract(Sample_ID, 'SW|FW|_C_|ESTUARY|RAINWATER'),
         Plot = gsub("_", "", Plot), 
         Grid = stringr::str_extract(Sample_ID, "B4|C3|C6|D5|E3|F4|F6|H3|H6|I5") ,
         Date = stringr::str_extract(Sample_ID, "[0-9]{8}"),
         Depth = stringr::str_extract(Sample_ID, "15CM|30CM|50CM"),
         T_num = stringr::str_extract(Sample_ID, "T0|T1|T2|T3|T4|T5|T6|HR0|HR1|HR2|HR3|HR4|HR5|HR6|HR7"),
         TOD = stringr::str_extract(Sample_ID, "AM|MID|PM"), 
         Sample_Type = stringr::str_extract(Sample_ID, "SOURCE"), 
         Sample_Type = replace_na(Sample_Type, "PW"), 
         
         Sample_ID_formatted = paste("TMP", Sample_Type, Plot, Grid, Depth, T_num, Date, TOD, sep = "_"), 
         Sample_ID_formatted = gsub("_NA", "", Sample_ID_formatted)) %>% 
  select(-Sample_ID)


####Nutrients####
Nutrients <- read.csv("Nutrients/COMPASS_TEMPEST_Nutrient_AllData.csv")
Nutrients1 <- Nutrients %>%
  rename(
    NOx_mgL = NOx_Conc_mgL, 
    NOx_uM = NOx_Conc_uM, 
    NH3_mgL = NH3_Conc_mgL, 
    NH3_uM = NH3_Conc_uM, 
    PO4_mgL = PO4_Conc_mgL, 
    PO4_uM = PO4_Conc_uM
  ) %>%
  dplyr::select(c("Sample_ID", "NOx_mgL", "NOx_uM", "NOx_Conc_Flag", "NH3_mgL", "NH3_uM",  "NH3_Conc_Flag", "PO4_mgL", "PO4_uM", "PO4_Conc_Flag")) %>% 
  mutate(Sample_ID = toupper (Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_15_", "_15CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_30_", "_30CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_50_", "_50CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("RAINWATER_DEC10-12_2024", "RAINWATER_20241212", Sample_ID))  %>% 
  distinct() 


Nutrients2 <- Nutrients1 %>%
  mutate(Plot = stringr::str_extract(Sample_ID, 'SW|FW|_C_|ESTUARY|RAINWATER'),
         Plot = gsub("_", "", Plot), 
         Grid = stringr::str_extract(Sample_ID, "B4|C3|C6|D5|E3|F4|F6|H3|H6|I5") ,
         Date = stringr::str_extract(Sample_ID, "[0-9]{8}"),
         Depth = stringr::str_extract(Sample_ID, "15CM|30CM|50CM"),
         T_num = stringr::str_extract(Sample_ID, "T0|T1|T2|T3|T4|T5|T6|HR0|HR1|HR2|HR3|HR4|HR5|HR6|HR7"),
         TOD = stringr::str_extract(Sample_ID, "AM|MID|PM"), 
         Sample_Type = stringr::str_extract(Sample_ID, "SOURCE"), 
         Sample_Type = replace_na(Sample_Type, "PW"), 
         
         Sample_ID_formatted = paste("TMP", Sample_Type, Plot, Grid, Depth, T_num, Date, TOD, sep = "_"), 
         Sample_ID_formatted = gsub("_NA", "", Sample_ID_formatted)) %>% 
  select(-Sample_ID)



####SO4/Cl####
SO4_Cl <- read.csv("Sulfate_Chloride/COMPASS_TEMPEST_SO4_Cl_AllData.csv")

SO4_Cl1 <- SO4_Cl %>%
  dplyr::select(c("Sample_ID", "SO4_ppm", "SO4_mM", "SO4_Conc_flag", "Cl_ppm", "Cl_mM", "Cl_Conc_flag", "salinity")) %>% 
  mutate(Sample_ID = toupper (Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_15_", "_15CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_30_", "_30CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_50_", "_50CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("RAINWATER_20241212", "RAINWATER_20241212", Sample_ID)) %>% 
  distinct() 


SO4_Cl2 <- SO4_Cl1 %>%
  mutate(Plot = stringr::str_extract(Sample_ID, 'SW|FW|_C_|ESTUARY|RAINWATER'),
         Plot = gsub("_", "", Plot), 
         Grid = stringr::str_extract(Sample_ID, "B4|C3|C6|D5|E3|F4|F6|H3|H6|I5") ,
         Date = stringr::str_extract(Sample_ID, "[0-9]{8}"),
         Depth = stringr::str_extract(Sample_ID, "15CM|30CM|50CM"),
         T_num = stringr::str_extract(Sample_ID, "T0|T1|T2|T3|T4|T5|T6|HR0|HR1|HR2|HR3|HR4|HR5|HR6|HR7"),
         TOD = stringr::str_extract(Sample_ID, "AM|MID|PM"), 
         Sample_Type = stringr::str_extract(Sample_ID, "SOURCE"), 
         Sample_Type = replace_na(Sample_Type, "PW"), 
         
         Sample_ID_formatted = paste("TMP", Sample_Type, Plot, Grid, Depth, T_num, Date, TOD, sep = "_"), 
         Sample_ID_formatted = gsub("_NA", "", Sample_ID_formatted)) %>% 
  select(-Sample_ID)


####Sulfide####
Sulfide <- read.csv("Sulfide/COMPASS_TEMPEST_Sulfide_AllData.csv")
Sulfide1 <- Sulfide %>%
  dplyr::select(c("Sample_ID", "H2S_mean_uM", "H2S_sd_uM", "H2S_cv", "H2S_Conc_flag", "H2S_cv_flag")) %>% 
  mutate(Sample_ID = toupper (Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_15_", "_15CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_30_", "_30CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_50_", "_50CM_", Sample_ID)) %>% 
  distinct() 


Sulfide2 <- Sulfide1 %>%
  mutate(Plot = stringr::str_extract(Sample_ID, 'SW|FW|_C_|ESTUARY|RAINWATER'),
         Plot = gsub("_", "", Plot), 
         Grid = stringr::str_extract(Sample_ID, "B4|C3|C6|D5|E3|F4|F6|H3|H6|I5") ,
         Date = stringr::str_extract(Sample_ID, "[0-9]{8}"),
         Depth = stringr::str_extract(Sample_ID, "15CM|30CM|50CM"),
         T_num = stringr::str_extract(Sample_ID, "T0|T1|T2|T3|T4|T5|T6|HR0|HR1|HR2|HR3|HR4|HR5|HR6|HR7"),
         TOD = stringr::str_extract(Sample_ID, "AM|MID|PM"), 
         Sample_Type = stringr::str_extract(Sample_ID, "SOURCE"), 
         Sample_Type = replace_na(Sample_Type, "PW"), 
         
         Sample_ID_formatted = paste("TMP", Sample_Type, Plot, Grid, Depth, T_num, Date, TOD, sep = "_"), 
         Sample_ID_formatted = gsub("_NA", "", Sample_ID_formatted)) %>% 
  select(-Sample_ID)


####pH####
pH <- read.csv("pH/COMPASS_TEMPEST_pH_AllData.csv")
colnames(pH)
pH <- pH %>%
  mutate(Sample_ID = toupper(Sample_ID)) %>% 
  dplyr::select(c("Sample_ID", "pH", "collection_temp_C", "temperature_flag", "pH_flag")) %>% 
  distinct() %>% 
  filter(!(Sample_ID == "TMP_SW_SOURCEWATER_20230607_1255_15CM" & temperature_flag == "temperature not recorded")) %>% 
  filter(!(Sample_ID == "TMP_ESTUARY_SOURCEWATER_20230607_1500_15CM" & temperature_flag == "temperature not recorded")) %>% 
  filter(!(Sample_ID == "TMP_FW_SOURCEWATER_20230607_1519_15CM" & temperature_flag == "temperature not recorded"))



```

##Combine data
```{r}
df_list <- list(DOC2, Nutrients2, SO4_Cl2, Sulfide2)
merged_df <- df_list %>% reduce(full_join)
```

##Need to figure out duplicates
```{r}
##Need to figure out duplicates
df_duplicates <- merged_df %>%
  group_by(Sample_ID_formatted) %>%
  filter(n() > 1) %>%
  ungroup()

##Fix SO4/Cl duplicates
df_duplicates_SO4 <- SO4_Cl2 %>%
  group_by(Sample_ID_formatted) %>%
  filter(n() > 1) %>%
  ungroup()
# lots of duplicate SO4_Cl rows removed - should do this in collated SO4_Cl data
# 2024 Estuary sourcewater was incorrectly all labelled AM, some should be PM - DONE
## Some samples were ran twice in COMPASS_TEMPEST_20230603 and 20230605 SO4/Cl run, sometimes the values are similar and sometimes very different. Not sure what happened here.
## TMP_PW_SW_F4_15CM_20241213 ran twice, different Cl values

##Fix DOC duplicates
df_duplicates_DOC <- DOC2 %>%
  group_by(Sample_ID_formatted) %>%
  filter(n() > 1) %>%
  ungroup()
## 20230607_PM samples ran twice, sometimes the values are similar and sometimes very different. 
## TMP_PW_SW_C3_15CM_T3_20240612 ran twice, different values

##Fix Nutrient duplicates
df_duplicates_Nutrients <- Nutrients2 %>%
  group_by(Sample_ID_formatted) %>%
  filter(n() > 1) %>%
  ungroup()
# 202300606 entered incorrectly, fixed 
# TEMPEST spelled incorrectly, fixed 
## TMP_C_C6_20230515 has zeroes for NOx in one run but not the other, the zero run was second but doesn't say it was a dilution, not sure what happened here. 
## Estuary sourcewater 20240611, 20240612, 20240613 ran twice

##Fix Sulfide duplicates
df_duplicates_Sulfide <- Sulfide2 %>%
  group_by(Sample_ID_formatted) %>%
  filter(n() > 1) %>%
  ungroup()


##Fix pH duplicates
# df_duplicates_pH <- pH2 %>%
#   group_by(Sample_ID_formatted) %>%
#   filter(n() > 1) %>%
#   ungroup()
##lots of duplicate pH rows removed - should do this in collated pH data
# TMP_SW_SOURCEWATER_20230607_1255_15CM has two entries? One says taken with YSI, no temperature - removed 
# TMP_FW_SOURCEWATER_20230607_1519_15CM has two entries? One has no temperature - removed
# TMP_ESTUARY_SOURCEWATER_20230607_1500_15CM has two entries? One has no temperature - removed 

```


## Pull in active porewater tracking inventory sheet from Google Drive: 
```{r rest of metadata, include=FALSE}

#Run these to pull the TEMPEST porewater metadata into GitHub if not already there
inventory_directory <- "https://docs.google.com/spreadsheets/d/1sFWq-WKhemPzbOFInqhCu_Lx0lsO6a_Z/edit#gid=496164093"

drive_download(inventory_directory, overwrite = TRUE)

sheet_names <- excel_sheets("TEMPEST_PorewaterInventory_May2022_Present.xlsx")
sheet_names

raw_metadata_lys <- read_excel("TEMPEST_PorewaterInventory_May2022_Present.xlsx", sheet = "Porewater - Individual", skip = 3)

raw_metadata_sw <- read_excel("TEMPEST_PorewaterInventory_May2022_Present.xlsx", sheet = "Source Water", skip = 3)

```


## Create similar sample IDs for matching to samples 
```{r pull in metadata for later, include=FALSE}

#Create IDs from what was collected for comparison later
##Lysimeter
raw_metadata_lys1 <- raw_metadata_lys %>%
  mutate(Sample_ID = toupper (Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_15_", "_15CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_30_", "_30CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_50_", "_50CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("1OF1", "T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("1OF2", "T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("1OF3", "T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("2OF2", "T2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("2OF3", "T2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("3OF3", "T3", Sample_ID)) %>% 
  mutate(Sample_ID = ifelse(str_detect(Sample_ID, "SOURCE"), gsub("20220622_T", "20220622_HR", Sample_ID), Sample_ID)) %>% 
  mutate(Sample_ID = gsub("RAIN_20241212", "RAINWATER_20241212", Sample_ID))

raw_metadata_lys2 <- raw_metadata_lys1 %>%
  mutate(Plot = stringr::str_extract(Sample_ID, 'SW|FW|_C_|ESTUARY|RAINWATER'),
         Plot = gsub("_", "", Plot), 
         Grid = stringr::str_extract(Sample_ID, "B4|C3|C6|D5|E3|F4|F6|H3|H6|I5") ,
         Date = stringr::str_extract(Sample_ID, "[0-9]{8}"),
         Depth = stringr::str_extract(Sample_ID, "15CM|30CM|50CM"),
         T_num = stringr::str_extract(Sample_ID, "T0|T1|T2|T3|T4|T5|T6|HR0|HR1|HR2|HR3|HR4|HR5|HR6|HR7"),
         TOD = stringr::str_extract(Sample_ID, "AM|MID|PM"), 
         Sample_Type = stringr::str_extract(Sample_ID, "SOURCE"), 
         Sample_Type = replace_na(Sample_Type, "PW"), 
         
         Sample_ID_formatted = paste("TMP", Sample_Type, Plot, Grid, Depth, T_num, Date, TOD, sep = "_"), 
         Sample_ID_formatted = gsub("_NA", "", Sample_ID_formatted)) %>% 
  select(-Sample_ID) %>% 
  distinct(Sample_ID_formatted, .keep_all = TRUE) %>% 
  select(c("Evacuation_date_YYYYMMDD", "Collection_Date_YYYYMMDD", "Collection_Start_Time_24hrs", "Collection_End_Time_24hrs", "EST_EDT", "Notes", "Sample_ID_formatted"))


##Source Water
raw_metadata_sw1 <- raw_metadata_sw %>%
  mutate(Sample_ID = toupper (Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_15_", "_15CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_30_", "_30CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_50_", "_50CM_", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("1OF1", "T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("1OF2", "T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("1OF3", "T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("2OF2", "T2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("2OF3", "T2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("3OF3", "T3", Sample_ID)) %>% 
  mutate(Sample_ID = ifelse(str_detect(Sample_ID, "SOURCE"), gsub("20220622_T", "20220622_HR", Sample_ID), Sample_ID)) %>% 
  mutate(Sample_ID = gsub("RAIN_20241212", "RAINWATER_20241212", Sample_ID))

raw_metadata_sw2 <- raw_metadata_sw1 %>%
  mutate(Plot = stringr::str_extract(Sample_ID, 'SW|FW|_C_|ESTUARY|RAINWATER'),
         Plot = gsub("_", "", Plot), 
         Grid = stringr::str_extract(Sample_ID, "B4|C3|C6|D5|E3|F4|F6|H3|H6|I5") ,
         Date = stringr::str_extract(Sample_ID, "[0-9]{8}"),
         Depth = stringr::str_extract(Sample_ID, "15CM|30CM|50CM"),
         T_num = stringr::str_extract(Sample_ID, "T0|T1|T2|T3|T4|T5|T6|HR0|HR1|HR2|HR3|HR4|HR5|HR6|HR7"),
         TOD = stringr::str_extract(Sample_ID, "AM|MID|PM"), 
         Sample_Type = stringr::str_extract(Sample_ID, "SOURCE"), 
         Sample_Type = replace_na(Sample_Type, "PW"), 
         
         Sample_ID_formatted = paste("TMP", Sample_Type, Plot, Grid, Depth, T_num, Date, TOD, sep = "_"), 
         Sample_ID_formatted = gsub("_NA", "", Sample_ID_formatted)) %>% 
  select(-Sample_ID) %>% 
  distinct(Sample_ID_formatted, .keep_all = TRUE) %>% 
  select(c("Deployment_Date_YYYYMMDD", "Deployment_Time_24hrs" , "Collection_Date_YYYYMMDD", "Collection_Time_24hrs",  "EST_EDT", "Notes", "Sample_ID_formatted"))


##Combine lys and sw data
metadata <- bind_rows(raw_metadata_lys2, raw_metadata_sw2)

##Merge sample data with metadata
merged_df$Sample_ID_formatted <- toupper(merged_df$Sample_ID_formatted)
metadata$Sample_ID_formatted <- toupper(metadata$Sample_ID_formatted)


final_data <- merged_df %>%
  left_join(metadata, by = c("Sample_ID_formatted"))


final_data_dup <- final_data %>%
  group_by(Sample_ID_formatted) %>%
  filter(n() > 1) %>%
  ungroup()


```


## Write the alldata file out to the folder 
```{r, echo=FALSE}

##Order data by Year, Month, Day
# final_data1 <- final_data[order(final_data$Year, final_data$Month, final_data$Day, final_data$Zone, final_data$Lysimeter, final_data$Depth_cm),]

colnames(final_data)

final_data1 <- final_data %>% 
  mutate(Project = "COMPASS", 
         Region = "CB", 
         Site = "TEMPEST", 
         Depth_cm = gsub("CM", "", Depth)) %>% 
  rename(Sample_ID = Sample_ID_formatted, 
         NOx_flag = NOx_Conc_Flag, 
         NH3_flag = NH3_Conc_Flag, 
         PO4_flag = PO4_Conc_Flag, 
         SO4_flag = SO4_Conc_flag, 
         Cl_flag = Cl_Conc_flag, 
         H2S_flag = H2S_Conc_flag
         ) %>% 
  select(c("Project", "Region", "Site", "Sample_ID", "Plot", "Grid", "Date", "Depth_cm", "T_num", "TOD", "Sample_Type", 
           "Evacuation_date_YYYYMMDD", "Collection_Date_YYYYMMDD", "Collection_Start_Time_24hrs", "Collection_End_Time_24hrs", 
           "Deployment_Date_YYYYMMDD", "Deployment_Time_24hrs" , "Collection_Time_24hrs", "EST_EDT", "Notes", 
           "npoc_mgL", "npoc_uM", "npoc_flag", "tdn_mgL", "tdn_uM", "tdn_flag", 
           "NOx_mgL", "NOx_uM", "NOx_flag", "NH3_mgL", "NH3_uM", "NH3_flag", "PO4_mgL", "PO4_uM", "PO4_flag", 
           "SO4_ppm", "SO4_mM", "SO4_flag", "Cl_ppm", "Cl_mM", "Cl_flag", "salinity", 
           "H2S_mean_uM", "H2S_sd_uM", "H2S_cv", "H2S_flag"))


write.csv(final_data1, "COMPASS_TEMPEST_AllData_AllYears.csv", row.names = FALSE)

```

