---
title: "TEMPEST: Porewater ICP"
author: "2023-2025 Samples"
date: "`r Sys.Date()`"
output: html_document
---

\newpage

# SET UP

```{r setup, include=FALSE}
#Set working directory
knitr::opts_knit$set(root.dir = "C:/Users/ashmo/OneDrive - Arizona State University/Data/TEMPEST/Porewater/01_RawMicroplateData/ICP")

library(googlesheets4)
library(googledrive)
library(tidyverse)
library(data.table)
library(plater)
library(openxlsx)
library(lubridate)
library(patchwork)
```


# USEFUL FUNCTIONS

```{r,include=FALSE}
cal_curve<-function(Conc_uM,ABS){
    model<-lm(ABS~Conc_uM)
    slope<-summary(model)$coefficients[2, 1]
    intercept<-summary(model)$coefficients[1, 1]
     R2<-summary(model)$r.squared
  return(data.frame(slope=slope,intercept=intercept,R2=R2))
}


#function to calculate percent difference
calc_percent_diff<-function(dup,original){
  avg<-(dup+original)/2
  percent_diff<-((abs(original-dup))/avg)*100
  return(percent_diff=percent_diff)
}


#Percent error
calc_percent_error<-function(chk,expected){
  percent_error<-(abs((chk-expected))/expected)*100
  return(percent_error=percent_error)
}
```


# April 15, 2026 - Run 1

## Metal Standard Curve Checks

```{r Metal Standard Curve Checks, echo = FALSE, message = FALSE, warning = FALSE}
run_date<-"04/15/2026"


##Read in blank standard
std_blank <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(1:2))

##Read in metals standards - there has to be a better way to do this
M_0.03 <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(3:4))
M_0.1 <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(5:6))
M_0.3_10 <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(7:11))
M_30 <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(12:13))
M_100 <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(14:15))
 
#COMBINE STANDARDS
M_stds <- bind_rows(M_0.03,M_0.1,M_0.3_10,M_30,M_100)


M_stds <- M_stds %>%
  #COMBINE WITH STANDARD BLANK
  #SELECT ONLY COLUMNS MEASURED IN M_STDS
  bind_rows(std_blank %>% select(any_of(colnames(M_stds))))%>% 
  #ADD EXPECTED CONCENTRATIONS OF STANDARDS
    separate_wider_delim(Sample.Id,names = c("Curve","Expected_Conc_ppm"),delim = " ",
                       too_many = "merge")%>%
  mutate(Expected_Conc_ppm = if_else(str_detect(Expected_Conc_ppm,"Blank"),0,as.numeric(Expected_Conc_ppm)))%>%
  #REMOVE INTERNAL STANDARDS
  select(-contains("(IS)"))%>%
  select(Curve, Expected_Conc_ppm,contains("(cps)"))%>%
  pivot_longer(cols = contains("(cps)"),
    names_to = "Element",
    values_to = "cps",
    values_drop_na = TRUE)

#CALCULATE R2
M_stds_curve<-M_stds%>%
  group_by(Element)%>%
  summarise(cal_curve(Expected_Conc_ppm,cps))%>%
  mutate(Run_Date = run_date)


#labels for plots 
data_text<-data.frame(
  Element = M_stds_curve$Element,
  label = round(M_stds_curve$R2,4)
)


p<-ggplot(M_stds,aes(x=Expected_Conc_ppm,y=cps))+
  geom_point()+
  geom_smooth(method="lm",se=FALSE)+
  facet_wrap(~Element,scales="free_y")+
  geom_text(
    data    = data_text,
    mapping = aes(x = Inf, y = Inf, label = label),
    hjust   = 1.1,
    vjust   = 5)+
  ggtitle(run_date)
  

print(p)

print(M_stds_curve)



```

## P, S, and Si Standard Curve Checks
```{r P Standard Curve Checks, echo = FALSE, message = FALSE, warning = FALSE}

#READ IN P STANDARDS
P_stds <- read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet = "Corrected Intensities", rows = c(16:23))


#COMBINE WITH BLANK
P_stds <- P_stds %>%
  bind_rows(std_blank)%>%
  select(Sample.Id:`Ga.radial.(IS).(cps)`)%>%
  #REMOVE INTERNATL STANDARDS
  select(-contains("(IS)"))%>%
  #ADD EXPECTED CONCENTRATIONS OF STANDARDS
    separate_wider_delim(Sample.Id,names = c("Curve","Expected_Conc_ppm"),delim = " ",
                       too_many = "merge")%>%
  mutate(Expected_Conc_ppm = if_else(str_detect(Expected_Conc_ppm,"Blank"),0,as.numeric(Expected_Conc_ppm)))%>%
  select(Curve, Expected_Conc_ppm,contains("(cps)"))%>%
  pivot_longer(cols = contains("(cps)"),
    names_to = "Element",
    values_to = "cps",
    values_drop_na = TRUE)


#CALCULATE R2
P_stds_curve<-P_stds%>%
  group_by(Element)%>%
  summarise(cal_curve(Expected_Conc_ppm,cps))%>%
  mutate(Run_Date = run_date)



#LABELS FOR PLOTS
data_text<-data.frame(
  Element = P_stds_curve$Element,
  label = round(P_stds_curve$R2,4)
)

#PLOT
p<-ggplot(P_stds,aes(x=Expected_Conc_ppm,y=cps))+
  geom_point()+
  geom_smooth(method="lm",se=FALSE)+
  facet_wrap(~Element,scales="free_y")+
  geom_text(
    data    = data_text,
    mapping = aes(x = Inf, y = Inf, label = label),
    hjust   = 1.1,
    vjust   = 5)+
  ggtitle(run_date)
  

print(p)

print(P_stds_curve)

```

#Import sample data

```{r,include=FALSE}
dat<-read.xlsx("20260415_AM_TMP_PW_Results.xlsx", sheet =  "Conc. in Calib Units", startRow = 24)

dat <- dat %>% 
  select(-1)
```


## Asses Metal Check Standards 
```{r,echo=FALSE, warning = FALSE}

# Pull out M check standards
M_chks_raw <- dat %>%
  filter(str_detect(Sample.Id,"M "))

# Remove percentage values and any S/P/Si stds
M_chks_raw <- M_chks_raw %>% 
  select(-contains("(IS)"), -contains("S."), -contains("P."), -contains("Si."))%>%
  
  # ADD EXPECTED CONCENTRAITON
  separate_wider_delim(Sample.Id,names = c("Curve","Expected_Conc_ppm"),delim = " ",
                       too_many = "merge")%>%
  mutate(Expected_Conc_ppm = if_else(str_detect(Expected_Conc_ppm,"Blank"),0,as.numeric(Expected_Conc_ppm)))%>%
  mutate(rep = row_number())


# CALCULATE PERCENT ERROR 
 
M_chks_pe<- M_chks_raw %>%
  select(rep, Curve, Expected_Conc_ppm,contains("mg/L)"))%>%
  pivot_longer(cols = contains("(mg/L)"),
    names_to = "Element",
    values_to = "ppm",
    values_drop_na = TRUE)%>%
  #CONCENTRATION OF SR IS LOWER THAN OTHER ELEMENTS
  mutate(Expected_Conc_ppm = if_else(str_detect(Element,"Sr"),Expected_Conc_ppm/10,Expected_Conc_ppm))%>%
  mutate(percent_error = calc_percent_error(ppm,Expected_Conc_ppm))%>%
  mutate(M_chks_flag = ifelse(abs(percent_error)<=10,"PASS","FAIL"))

#data frame of expected concentrations for hline on graph
#necessary because Sr has a different expected concentrations from other elements
hline_dat<-data.frame(
  Element = M_chks_pe$Element,
  intercept_value = M_chks_pe$Expected_Conc_ppm
)

  
p<-ggplot(M_chks_pe, aes(x=rep,y=ppm))+
  facet_wrap(~Element,scales = "free_y")+
  #dashed line for expected concentration
  geom_hline(data=hline_dat, aes(yintercept = intercept_value), linetype="dashed", color = "black", linewidth=1) + 
  geom_bar(stat = "identity", position = position_dodge(),aes(fill=M_chks_flag))+
  scale_fill_manual(values = c("PASS" = "chartreuse4", "FAIL" = "darkred"),
                    name = "% error < 10%")+
  labs(x="",y="Concentration (mg/L)")

print(p)


chks_percent <- M_chks_pe%>%
  group_by(Element)%>%
  summarise(Pass_percent = mean(abs(percent_error)<=10)*100,
            RSD = (abs(sd(ppm))/mean(ppm))*100)%>%
  mutate(PE_flag = ifelse(Pass_percent >= 80,"PASS","FAIL"),
         RSD_flag = ifelse(RSD<=15,"PASS","FAIL"))%>%
  filter(PE_flag == "FAIL")
 

print(chks_percent)

```

## Assess P, S, and Si Check Standards
```{r,echo=FALSE, warning = FALSE}
# Pull out M check standards
P_chks_raw <- dat %>%
  filter(str_detect(Sample.Id,"P "))

# Remove percentage values and any M stds
P_chks_raw <- P_chks_raw %>% 
  select(1:6, `P.178.221.(mg/L)`,`P.213.617.(mg/L)`,`S.radial.(mg/L)`,`S.axial.(mg/L)`,`Si.axial.(mg/L)` )%>%
  
  # ADD EXPECTED CONCENTRAITON
  separate_wider_delim(Sample.Id,names = c("Curve","Expected_Conc_ppm"),delim = " ",
                       too_many = "merge")%>%
  mutate(Expected_Conc_ppm = if_else(str_detect(Expected_Conc_ppm,"Blank"),0,as.numeric(Expected_Conc_ppm)))%>%
  mutate(rep = row_number())


# CALCULATE PERCENT ERROR 
 
P_chks_pe<- P_chks_raw %>%
  select(rep, Curve, Expected_Conc_ppm,contains("mg/L)"))%>%
  pivot_longer(cols = contains("(mg/L)"),
    names_to = "Element",
    values_to = "ppm",
    values_drop_na = TRUE)%>%
  #PERCENT ERROR CALCULATIONS
  mutate(percent_error = calc_percent_error(ppm,Expected_Conc_ppm))%>%
  mutate(P_chks_flag = ifelse(abs(percent_error)<=10,"PASS","FAIL"))

#data frame of expected concentrations for hline on graph
#necessary because Sr has a different expected concentrations from other elements
hline_dat<-data.frame(
  Element = P_chks_pe$Element,
  intercept_value = P_chks_pe$Expected_Conc_ppm
)

  
p<-ggplot(P_chks_pe, aes(x=rep,y=ppm))+
  facet_wrap(~Element,scales = "free_y")+
  #dashed line for expected concentration
  geom_hline(data=hline_dat, aes(yintercept = intercept_value), linetype="dashed", color = "black", linewidth=1) + 
  geom_bar(stat = "identity", position = position_dodge(),aes(fill=P_chks_flag))+
  scale_fill_manual(values = c("PASS" = "chartreuse4", "FAIL" = "darkred"),
                    name = "% error < 10%")+
  labs(x="",y="Concentration (mg/L)")

print(p)


P_chks_percent <- P_chks_pe%>%
  group_by(Element)%>%
  summarise(Pass_percent = mean(abs(percent_error)<=10)*100,
            RSD = (abs(sd(ppm))/mean(ppm))*100)%>%
  mutate(PE_flag = ifelse(Pass_percent >= 80,"PASS","FAIL"),
         RSD_flag = ifelse(RSD<=15,"PASS","FAIL"))%>%
  filter(PE_flag == "FAIL")
 

print(P_chks_percent)


```

## Check Internal Standards
```{r,echo=FALSE, warning = FALSE}
IS_stds<- dat %>%
  select(1:6, contains("(IS"))%>%
   mutate(rep = row_number())%>%
  pivot_longer(cols = contains("(IS)"),
    names_to = "Element",
    values_to = "Percent",
    values_drop_na = TRUE)%>%
  mutate(IS_flag = case_when(
    Percent > 110 | Percent < 90 ~ "FAIL",
    Percent < 110 & Percent > 90 ~ "PASS"
  ))


p_IS<-ggplot(IS_stds, aes(x=rep,y=Percent))+
  geom_hline(yintercept = 100, color = 'black',linetype='dashed')+
  geom_line()+
  geom_point(aes(color=IS_flag))+
  facet_wrap(~Element)+
  scale_color_manual(values = c("PASS" = "chartreuse4", "FAIL" = "darkred"),
                    name = "% error < 10%")+
  coord_cartesian(ylim=c(80,120))

print(p_IS)


print(IS_stds %>% filter(IS_flag == "BAD"))


```

## Additional Checks 

NIST 1643f and Multi-elemental standard (QCS) are used as additional checks with a 10x dilution 

```{r,echo=FALSE, warning = FALSE}
DF<-10 # dilution factor 

#Make data frame of expected values for each additional check

##QCS - Multi-elemental standard
QCS<- data.frame(
  Element = c("Al", "B","Ca","Fe","K","Mg","Mn","Na","P","S","Si","Sr","Zn"),
  Expected_Conc_ppm = c(99.8, 49, 98.9,99.9,49.78,99.0,10.03,101.1,49.50,99.1,99.1,9.92,50.3)
)

QCS<-QCS%>%
  #Account for dilution factor (10)
  mutate(Expected_Conc_ppm = Expected_Conc_ppm/DF )


#Pull out check samples 
QCS_dat<-dat%>%
  filter(str_detect(Sample.Id,"QCS"))%>%
  #remove internal standards
  select(-contains("(IS)"))%>%
  mutate(rep=row_number())%>%
  pivot_longer(cols = contains("(mg/L)"),
    names_to = "Element",
    values_to = "ppm",
    values_drop_na = TRUE)%>%
  #MERGE WITH DATA FRAME OF EXPECTED VALUES
  separate_wider_delim(Element,delim =".",names = c("Element","Measurement.type","Units"),too_many = "merge")%>%
  left_join(QCS, by= "Element")

QCS_pe<-QCS_dat%>%
  mutate(QCS_pe = calc_percent_error(ppm,Expected_Conc_ppm))%>%
  mutate(QCS_flag = ifelse(abs(QCS_pe)<=10,"PASS","FAIL"))


hline_dat<-data.frame(
  Element = QCS_pe$Element,
  intercept_value = QCS_pe$Expected_Conc_ppm
)

  
p<-ggplot(QCS_pe, aes(x=rep,y=ppm))+
  facet_wrap(~Element,scales = "free_y")+
  #dashed line for expected concentration
  geom_hline(data=hline_dat, aes(yintercept = intercept_value), linetype="dashed", color = "black", linewidth=1) + 
  geom_bar(stat = "identity", position = position_dodge(),aes(fill=QCS_flag))+
  scale_fill_manual(values = c("PASS" = "chartreuse4", "FAIL" = "darkred"),
                    name = "% error < 10%")+
  labs(x="",y="Concentration (mg/L)")+
  ggtitle("QCS Multi-elemental Standard (1:10) check")

print(p)


```

```{r}
##NIST 1643f 
NIST<-data.frame(
  Element = c("Al", "B","Ca","Fe","K","Mg","Mn","Na","Sr","Zn"),
  Expected_Conc_ug.L = c(133.8,152.3,29430,93.44,1932.6,7454,37.14,18830,314,74.4)
)

NIST<-NIST %>%
  #convert to ppm (mg/L)
  group_by(Element)%>%
  summarise(Expected_Conc_ppm = Expected_Conc_ug.L/1000)%>%
  #account for dilution factor (10)
  mutate(Expected_Conc_ppm = Expected_Conc_ppm/DF)
  

NIST_dat<-dat%>%
  filter(str_detect(Sample.Id,"NIST"))%>%
  #remove internal standards
  select(-contains("(IS)"))%>%
  mutate(rep=row_number())%>%
  pivot_longer(cols = contains("(mg/L)"),
    names_to = "Element",
    values_to = "ppm",
    values_drop_na = TRUE)%>%
  #MERGE WITH DATA FRAME OF EXPECTED VALUES
  separate_wider_delim(Element,delim =".",names = c("Element","Measurement.type","Units"),too_many = "merge")%>%
  left_join(NIST, by= "Element")

NIST_pe<-NIST_dat%>%
  filter(!is.na(Expected_Conc_ppm))%>%
  mutate(NIST_pe = calc_percent_error(ppm,Expected_Conc_ppm))%>%
  mutate(NIST_flag = ifelse(abs(NIST_pe)<=10,"PASS","FAIL"))


hline_dat<-data.frame(
  Element = NIST_pe$Element,
  intercept_value = NIST_pe$Expected_Conc_ppm
)

  
p_axial<-NIST_pe%>%
  filter(Measurement.type=="axial")%>%
  mutate(intercept_value = Expected_Conc_ppm)%>%
  ggplot(aes(x=rep,y=ppm))+
  facet_wrap(~Element,scales = "free_y",drop=TRUE)+
  #dashed line for expected concentration
  geom_hline(aes(yintercept = intercept_value), linetype="dashed", color = "black", linewidth=1) + 
  geom_bar(stat = "identity", position = position_dodge(),aes(fill=NIST_flag))+
  scale_fill_manual(values = c("PASS" = "chartreuse4", "FAIL" = "darkred"),
                    name = "% error < 10%")+
  labs(x="",y="Concentration (mg/L)",title = "NIST 1643f Checks",subtitle = "Axial")

p_radial<-NIST_pe%>%
  filter(Measurement.type=="radial")%>%
  mutate(intercept_value = Expected_Conc_ppm)%>%
  ggplot(aes(x=rep,y=ppm))+
  facet_wrap(~Element,scales = "free_y",drop=TRUE)+
  #dashed line for expected concentration
  geom_hline(aes(yintercept = intercept_value), linetype="dashed", color = "black", linewidth=1) + 
  geom_bar(stat = "identity", position = position_dodge(),aes(fill=NIST_flag))+
  scale_fill_manual(values = c("PASS" = "chartreuse4", "FAIL" = "darkred"),
                    name = "% error < 10%")+
  labs(x="",y="Concentration (mg/L)",subtitle = "Radial")


p<-p_axial / p_radial + plot_layout(guides = "collect",heights = c(2,4))

print(p)



```





