---
title: "COMPASS_TEMPEST_Collate_DOC_2024_Data"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

files <- list.files(path = "tmp_doc_processed_data_2025", pattern = "\\.csv$", full.names = TRUE)

# 3. Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv) %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

all_data <- all_data[, -which(names(all_data) == "X")]

##Make Sample IDs match 2022/2023 data
all_data$Sample_ID <- paste0("TMP_", all_data$Vial_ID)
all_data$Sample_ID <- gsub("_DOC_", "_", all_data$Sample_ID)

colnames(all_data)

final_data <- all_data %>%
    mutate(
      Project = "COMPASS", 
      Site = "TEMPEST", 
      ) %>%
  rename (
    Analyte = sample_type
  ) %>%
    select (-c(date, Vial_ID)) 


```

## Write the 2023 file out to the folder 
```{r, echo=FALSE}

write.csv(final_data, "COMPASS_TEMPEST_DOC_2025.csv", row.names = FALSE)

```

