---
title: "COMPASS_TEMPEST_Collate_Dionex_2024_Data"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

files <- list.files(path = "tmp_doc_processed_data_2024", pattern = "\\.csv$", full.names = TRUE)

# 3. Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv) %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

all_data <- all_data[, -which(names(all_data) == "X")]

##Make Sample IDs match 2022/2023 data
all_data$Sample_ID <- paste0("TMP_", all_data$Vial_ID)
all_data$Sample_ID <- gsub("_DOC_", "_", all_data$Sample_ID)

all_data$Sample_ID <- gsub("TMP_TMP_CTRL_Rain_20241212", "TMP_C_Rain_20241212", all_data$Sample_ID)
all_data$Sample_ID <- gsub("TMP_TMP_FW_Rain_20241212", "TMP_FW_Rain_20241212", all_data$Sample_ID)
all_data$Sample_ID <- gsub("TMP_TMP_SW_Rain_20241212", "TMP_SW_Rain_20241212", all_data$Sample_ID)

all_data$Sample_ID <- gsub("SOURCEWATER", "SOURCE", all_data$Sample_ID)

all_data <- all_data %>% 
  mutate(grid = ifelse(str_detect(Sample_ID, "SOURCE"), "Source", grid))

colnames(all_data)

final_data <- all_data %>%
    mutate(
      Project = "COMPASS", 
      Site = "TEMPEST", 
      ) %>%
  rename (
    Analyte = sample_type
  ) %>%
    select (-c(Type, date, Vial_ID)) 


```

## Write the 2023 file out to the folder 
```{r, echo=FALSE}

write.csv(final_data, "COMPASS_TEMPEST_DOC_2024.csv", row.names = FALSE)

```



##Plot Sourcewater over Time
```{r Sourcewater over Time}

##Summarize DOC by Date and Grid
# DOC_avg <- data_plotting %>%
#   group_by(Collection_Date_formatted, plot_1) %>%
#    dplyr::summarize(mean_npoc = mean(npoc_mgL, na.rm=TRUE),
#             sd_npoc = sd(npoc_mgL, na.rm=TRUE),
#             mean_tdn = mean(tdn_mgL, na.rm=TRUE),
#             sd_tdn = sd(tdn_mgL, na.rm=TRUE))
# 
# # Define the specific date breaks you want to display
# specific_breaks <- as.Date(c("2022-01-01","2023-01-01","2024-01-01", "2025-01-01"))

SCE_data <- subset(final_data, str_detect(final_data$Sample_ID, "SOURCE"))

##Convert Collection Date into Date format
SCE_data$Collection_DateTime <-
  paste(
    SCE_data$Collection_Date_YYYYMMDD,
    sprintf("%04d", SCE_data$Collection_Time_24hrs)
  )

SCE_data$Collection_Date_formatted <-
  as.POSIXct(
    gsub("(\\d{2})(\\d{2})$", "\\1:\\2", SCE_data$Collection_DateTime),
    format = "%Y%m%d %H:%M"
  )

specific_breaks <- as.POSIXct(c("2024-06-11 00:00:00", 
                                "2024-06-12 00:00:00", 
                                "2024-06-13 00:00:00"))

viz_npoc_sce_plot <- ggplot(SCE_data, aes(x = Collection_Date_formatted, y = npoc_mgL, color = plot)) +
  geom_point(size = 3) + 
  geom_line() + 
  facet_wrap( ~ plot, ncol = 1, scale = "free") +
  scale_color_manual(values = c(
    "Control" = "springgreen2",
    "FW" = "cyan2",
    "SW" = "violetred2", 
    "Estuary" = "maroon"
  )) +
  theme_classic() +
  labs(x = "Date Time", y = "NPOC (mg/L)") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(text = element_text(size = 30)) + 
  scale_x_datetime(breaks = specific_breaks, 
                   limits = c(
    as.POSIXct("2024-06-11 00:00:00"),
    as.POSIXct("2024-06-13 23:59:59"))) + 
  # scale_x_datetime(date_breaks = "24 hours", 
  #                  date_minor_breaks = "1 hour", 
  #                  date_labels = "%B %d %H:%M", 
  #                  limits = as.POSIXct(c("2024-06-11 00:00:00", "2024-06-13 24:00:00"))) +
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm")) + 
  theme(legend.position = "none") + 

  theme(
    plot.margin = margin(t = 15, r = 35, b = 15, l = 15, unit = "pt"),
    axis.title.x = element_text(margin = margin(t = 15))
  )

viz_npoc_sce_plot

# Save as a PNG
png("COMPASS_SynopticCB_NPOC_SCE_2024.png", width = 2000, height = 1200, res = 200)
print(viz_npoc_sce_plot)  # For ggplot objects, use print()
dev.off()
```

