---
title: "TEMPEST_Collate_Sulfide_2025_Data"
author: "Stephanie J. Wilson and Zoe Read"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

files <- list.files(pattern="Combined", full.names=TRUE, recursive = TRUE)

# Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv) %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

colnames(all_data)

final_data <- all_data %>%
  rename(
    H2S_mean_uM = H2S_mean, 
    H2S_sd_uM = H2S_sd
    ) %>%
  select(
    Project, Zone, Grid, Depth_cm, 
         Sample_ID, Source, Volume_mL, Collection_Date, 
         H2S_mean_uM, H2S_sd_uM, H2S_cv, H2S_Conc_flag, H2S_cv_flag, H2S_QAQC_flag, Dilution, 
         Analysis_rundate,  Run_notes, Field_notes
        # list columns in the order you want them
  )


```

## Write the 2023 file out to the folder 
```{r, echo=FALSE}

write.csv(final_data, "TEMPEST_Sulfide_2025.csv", row.names = FALSE)

```

